services:
  scenic:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_KEY=${REACT_APP_API_KEY}
        - REACT_APP_MOVIE_SERVER1=${REACT_APP_MOVIE_SERVER1}
        - REACT_APP_TV_SERVER1=${REACT_APP_TV_SERVER1}
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always

# Note: Create a .env file in the root directory with your TMDB API key before running.
